name = "discord-oidc"
main = "src/worker.ts"
compatibility_date = "2024-09-03"

workers_dev = true
send_metrics = true

kv_namespaces = [
  { binding = "KV", id = "0f6ab8a4e72e412babab23d740334e44" }
]