version: 2.1
orbs:
  node: circleci/node@6.3.0

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn check
          name: Run check
  deploy:
    executor: node/default
    steps:
      - run:
          command: yarn deploy
          name: Deploy

workflows:
  test_and_deploy:
    jobs:
      - build_and_test
      - deploy:
          context: cf-workers
          requires:
            - build_and_test # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: master # only deploy when on main
